name: Netlify Deploy
on:
  push:
    branches: [ master ]
  # schedule:
  #   - cron: '0 6 * * *'
env:
  DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out "master"
      uses: actions/checkout@v2
    - name: Set up Node V13
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Install dependencies 
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy to Netlify
      run: npm run deploy